name: Bug report (form-based)
description: File a bug/issue
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  attrivutes:
    label: Game/Engine/Component Name
    description: What are you reporting the issue for?
  validations:
    required: false
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Load the saved game...
      2. Click on this character...
      3. Choose '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Operating System**: Windows 11
        - **ScummVM Version**: 2.6.0
        - **Game version**: VGA Floppy 1.1
    value: |
        - Operating System:
        - ScummVM Version:
        - Game Version:
    render: markdown
  validations:
    required: false
- type: 
- type: textarea
  attributes:
    label: Save games, screenshots, and logs
    description: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      
      Save games must be compressed as a `.zip` file.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
