name: Bug report (form-based)
description: File a bug/issue
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  attributes:
    label: Game/Engine/Component Name (Freeform)
    description: What are you reporting the issue for?
  validations:
    required: false
- type: dropdown
  attributes:
    label: Game Name (Dropdown)
    description: What game are you reporting the issue for?
    options:
      - 11th Hour
      - 3 Skulls of the Toltecs
      - 7th Guest
      - AGI Fangame
      - "Amazon: Guardians of Eden"
      - Backyard Baseball
  validations:
    required: false
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Load the saved game...
      2. Click on this character...
      3. Choose '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Operating System**: Windows 11
        - **ScummVM Version**: 2.6.0
        - **Game version**: VGA Floppy 1.1
    value: |
        - Operating System: 
        - ScummVM Version: 
        - Game Version: 
    render: markdown
  validations:
    required: false
- type: dropdown
  attributes:
    label: ScummVM Version (Dropdown)
    description: What version of ScummVM are you running?
    multiple: false
    options:
      - label: 2.5.1 (Stable)
      - label: 2.6.0 (Pre-release)
      - label: Daily
  validations:
    required: true
- type: textarea
  attributes:
    label: Save games, screenshots, and logs
    description: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      
      Save games must be compressed as a `.zip` file.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
